// FullStack_Based/vue/Exercise/20201020/vuesyntax/src/components/CartList.vue
<template>
  <div>
    <div class="item" v-for="(item) in list" :key="item.id">
      <img :src="item.img" />
      <div class="name">{{ item.name }}</div>
      <div class="change">
        <a href="" @click.prevent="sub(item.id)">－</a>
        <input
          type="text"
          class="num"
          :value="item.num"
          @blur="change(item.id, $event)"
        />
        <a href="" @click.prevent="add(item.id)">＋</a>
      </div>
      <div class="del" @click="del(item.id)">×</div>
    </div>
  </div>
</template>

<script>
export default {
  name: "CartList",
  props: ["list"],
  // watch: {
  //   list() {
  //     console.log("数据发生变化")
  //   }
  // },
  methods: {
    change(id, event) {
      this.$emit("change", {
        type: "change",
        num: event.target.value,
        id
      });
    },
    sub(id) {
      this.$emit("change", {
        type: "sub",
        id
      });
    },
    add(id) {
      this.$emit("change", {
        type: "add",
        id
      });
    },
    del(id) {
      this.$emit("change", {
        type: "del",
        id
      });
    }
  }
};
</script>

<style></style>

// FullStack_Based/react/Exercise/20210510/shopping-cart/src/components/CartList/index.jsx
import React from "react"


class CartList extends React.Component {

  handlerDelete = (id)=>{
    this.props.deleteItem(id);
  }

  //改变数量事件
  handleChangeNum = (id,e) => {
    // console.log(e.target.dataset.num);
    //判断用户点击元素
    switch (e.target.dataset.num) {
      case 'add':
        this.props.changeNum(id,'add');
        break;
    
      case 'min':
        this.props.changeNum(id,'min');
        break;
      
      case 'blur':
        this.props.changeNum(id,'blur',e.target.value);
        break;
    }
  }

  render() {
    return (
      <div>
        {
          this.props.list.map(item=>(
            <div className="item">
            <img src={item.img} alt="" />
            <div className="name">{item.name}</div>
            <div className="change">
              {/* eslint-disable-next-line */}
              <a href="#" data-num='min' onClick={this.handleChangeNum.bind(this,item.id)}>－</a>
              <input type="text" className="num" data-num='blur' value={item.num} onChange={this.handleChangeNum.bind(this,item.id)}/>
              {/* eslint-disable-next-line */}
              <a href="#" data-num='add' onClick={this.handleChangeNum.bind(this,item.id)}>＋</a>
            </div>
            <div className="del" onClick={this.handlerDelete.bind(this,item.id)}>×</div>
          </div>
          ))
        }
      </div>
    )
  }
}

export default CartList;
